### ISSUE TITLE
If an absurd high ETH value is not sent in a cross chain function, it reverts with "LayerZero: not enough native for fees"

### ISSUE THREAD

**Issue by 0xTimepunk** [exp-table/pigeon#9]
Hi,

First of all, lovely library, thanks for creating it!

I have been using it in the tests of a cross chain protocol. In this protocol there is a cross chain function and I can't send just 1 eth as per your example in `_someCrossChainFunctionInYourContract()`, otherwise I get the error trace below:

![image](https://user-images.githubusercontent.com/45543880/218081811-c61c1be7-6662-4138-9a1f-c4a478731fc6.png)

What is more funny is if I increase this value to 5 or even 25 eth it doesn't work (check the value field in `UltraLightNodeV2::send`)

![image](https://user-images.githubusercontent.com/45543880/218082122-f6053a49-c1fc-40ad-a8aa-99c5de57a0a7.png)

But if I increase it to 50 eth the msg.value, the test case passes and everything operates normally (helper function of pigeon is called after).

After a few test runs, eventually this needs to increase again to 100 ETH even to pass. I find this behaviour absurd and wonder if you have any insight at what might be at play here?

The adapterParam for layer zero is being sent as an empty bytes for this test, just like your test example.

Thank you

**Comment by exp-table** [comment]
It's normal if you are using a chain whose token is priced low, such as Polygon. If your target is ETH, which is usually more expensive to execute code on than a L2, you will need to pay enough so the ETH gas costs are covered.
